In [1]:
import pandas as pd
import numpy as np

## 0-Dataset

In [6]:
df = pd.read_csv("All Categories.csv")

In [3]:
df.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,Meesho: Online Shopping App,Meesho,Shopping,15 MB,4.4,15L,10Cr+,3+
1,2,Shopee: Online Shopping,Shopee,Shopping,68 MB,4.1,76T,1Cr+,3+
2,3,Instagram,Instagram,Social,41 MB,4.3,13Cr,100Cr+,12+
3,4,"MX Player: Videos, OTT & Games",MX Media (formerly J2 Interactive),Video Players & Editors,36 MB,4.1,1Cr,100Cr+,3+
4,5,speedfiy,PRIME DIGITAL PTE. LTD.,Tools,12 MB,4.5,41T,1Cr+,3+

In [4]:
df.shape

(600, 9)

In [24]:
df = df[['Name','Category']]

In [25]:
df.head()

                             Name                 Category
0     Meesho: Online Shopping App                 Shopping
1         Shopee: Online Shopping                 Shopping
2                       Instagram                   Social
3  MX Player: Videos, OTT & Games  Video Players & Editors
4                        speedfiy                    Tools

## 1 - Dataset

In [7]:
df1 = pd.read_csv("Android Malware Detection.csv")

In [8]:
df1.head()

,Unnamed: 0,ACCESS_ALL_DOWNLOADS,ACCESS_CACHE_FILESYSTEM,ACCESS_CHECKIN_PROPERTIES,ACCESS_COARSE_LOCATION,ACCESS_FINE_LOCATION,ACCESS_LOCATION_EXTRA_COMMANDS,ACCESS_MOCK_LOCATION,ACCESS_NETWORK_STATE,ACCESS_SURFACE_FLINGER,...,WRITE_GSERVICES,WRITE_MEDIA_STORAGE,WRITE_PROFILE,WRITE_SECURE_SETTINGS,WRITE_SETTINGS,WRITE_SMS,WRITE_SOCIAL_STREAM,WRITE_SYNC_SETTINGS,WRITE_USER_DICTIONARY,Label
0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

## 2- Dataset

In [9]:
df2 = pd.read_csv("Android_Malware_Benign.csv")

In [10]:
df2.head()

,ACCESS_ALL_DOWNLOADS,ACCESS_CACHE_FILESYSTEM,ACCESS_CHECKIN_PROPERTIES,ACCESS_COARSE_LOCATION,ACCESS_COARSE_UPDATES,ACCESS_FINE_LOCATION,ACCESS_LOCATION_EXTRA_COMMANDS,ACCESS_MOCK_LOCATION,ACCESS_MTK_MMHW,ACCESS_NETWORK_STATE,...,com.android.launcher.permission.UNINSTALL_SHORTCUT,com.sec.android.iap.permission.BILLING,com.htc.launcher.permission.UPDATE_SHORTCUT,com.sec.android.provider.badge.permission.WRITE,android.permission.ACCESS_NETWORK_STATE,com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE,com.huawei.android.launcher.permission.READ_SETTINGS,android.permission.READ_SMS,android.permission.PROCESS_INCOMING_CALLS,Label
0,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,Malware
1,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,1,0,Malware
2,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,1,0,Malware
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Malware
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,Malware

## 3- Dataset

In [15]:
df3 = pd.read_csv("app_data.csv")

In [12]:
df3.head()

,Unnamed: 0,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,0,1,RTO Vehicle Information,Learn English In Hindi - Translator & Dictionary,Auto & Vehicles,21 MB,4.5,1L,1Cr+,3+
1,1,2,"Vahak: Book Online Truck, Load",Most Trusted Transporters from All India.,Auto & Vehicles,17 MB,3.8,3T,10L+,3+
2,2,3,"CARS24® – Buy Used Cars Online, Sell Car in 1 ...",CARS24 Services Private Limited,Auto & Vehicles,33 MB,4.4,1L,1Cr+,3+
3,3,4,BlackBuck Boss,BlackBuck,Auto & Vehicles,39 MB,4.1,27T,10L+,3+
4,4,5,CarDekho:New & Second Hand Car,Girnar Software Pvt. Ltd.,Auto & Vehicles,18 MB,4.5,1L,1Cr+,3+

In [26]:
df3 = df3[['Name','Category']]

In [28]:
df3.head()

                                                Name         Category
0                            RTO Vehicle Information  Auto & Vehicles
1                     Vahak: Book Online Truck, Load  Auto & Vehicles
2  CARS24® – Buy Used Cars Online, Sell Car in 1 ...  Auto & Vehicles
3                                     BlackBuck Boss  Auto & Vehicles
4                     CarDekho:New & Second Hand Car  Auto & Vehicles

## 4- Dataset

In [16]:
df4 = pd.read_csv("dataset-features-categories.csv")

In [17]:
df4.head()

             transact  API call signature
0  onServiceConnected  API call signature
1         bindService  API call signature
2     attachInterface  API call signature
3   ServiceConnection  API call signature
4   android.os.Binder  API call signature

## 5 - Dataset

In [18]:
df5 = pd.read_csv("googleplaystore_user_reviews.csv")

In [19]:
df5.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

## 6-Dataset

In [20]:
df6 = pd.read_csv("googleplaystore.csv")

In [21]:
df6.head()

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,7-Jan-18,1.0.0,4.0.3 and up
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,15-Jan-18,2.0.0,4.0.3 and up
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,1-Aug-18,1.2.4,4.0.3 and up
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,8-Jun-18,Varies with device,4.2 and up
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,20-Jun-18,1.1,4.4 and up

In [23]:
df6.shape

(10841, 14)

In [34]:
df6 = df6[['App','Category']]
df6.columns=['Name',"Category"]

In [35]:
df6.head()

                                                Name        Category
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN
1                                Coloring book moana  ART_AND_DESIGN
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN
3                              Sketch - Draw & Paint  ART_AND_DESIGN
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN

## Creating Final Dataset

In [36]:
final_df = pd.concat([df3[['Name','Category']], df[['Name','Category']], df6[['Name','Category']]])

In [37]:
final_df.head()

                                                Name         Category
0                            RTO Vehicle Information  Auto & Vehicles
1                     Vahak: Book Online Truck, Load  Auto & Vehicles
2  CARS24® – Buy Used Cars Online, Sell Car in 1 ...  Auto & Vehicles
3                                     BlackBuck Boss  Auto & Vehicles
4                     CarDekho:New & Second Hand Car  Auto & Vehicles

## Saving Dataset

In [38]:
final_df.to_csv("app_dataset_final.csv", index=False)