In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

## Importing Datasets

In [4]:
df1 = pd.read_csv('dataset.csv')

## 1- Dataset

In [5]:
df1.head()

,URL,URL_LENGTH,NUMBER_SPECIAL_CHARACTERS,CHARSET,SERVER,CONTENT_LENGTH,WHOIS_COUNTRY,WHOIS_STATEPRO,WHOIS_REGDATE,WHOIS_UPDATED_DATE,...,DIST_REMOTE_TCP_PORT,REMOTE_IPS,APP_BYTES,SOURCE_APP_PACKETS,REMOTE_APP_PACKETS,SOURCE_APP_BYTES,REMOTE_APP_BYTES,APP_PACKETS,DNS_QUERY_TIMES,Type
0,M0_109,16,7,iso-8859-1,nginx,263.0,NaN,NaN,10/10/2015 18:21,NaN,...,0,2,700,9,10,1153,832,9,2.0,1
1,B0_2314,16,6,UTF-8,Apache/2.4.10,15087.0,NaN,NaN,NaN,NaN,...,7,4,1230,17,19,1265,1230,17,0.0,0
2,B0_911,16,6,us-ascii,Microsoft-HTTPAPI/2.0,324.0,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0.0,0
3,B0_113,17,6,ISO-8859-1,nginx,162.0,US,AK,7/10/1997 4:00,12/09/2013 0:45,...,22,3,3812,39,37,18784,4380,39,8.0,0
4,B0_403,17,6,UTF-8,NaN,124140.0,US,TX,12/05/1996 0:00,11/04/2017 0:00,...,2,5,4278,61,62,129889,4586,61,4.0,0

In [20]:
df1['Type'].unique()

array([1, 0])

## 2- Dataset

In [6]:
df2 = pd.read_csv('DatasetForWebPageClassification.csv')

In [7]:
df2.head()

                                    url          label
0         https://www.alaskansunset.com     6 - Travel
1  https://www.realbusinessrescue.co.uk   0 - Business
2            https://sentinelpeakrv.com     6 - Travel
3             http://www.chesspals.com/      3 - Games
4         https://www.marengo.k12.al.us  1 - Education

In [19]:
df2['label'].unique()

array(['6 - Travel', '0 - Business', '3 - Games', '1 - Education',
       '5 - Sport', '4 - Health', '2 - Adult'], dtype=object)

In [21]:
df2 = df2[['url', 'label']]

In [34]:
df2['label'] = df2['label'].map({'6 - Travel': 0, '0 - Business': 0,'3 - Games': 0 ,'1 - Education':0 ,'5 - Sport': 0, '4 - Health': 0,'2 - Adult': 1})

In [35]:
df2.head()

                                    url  label
0         https://www.alaskansunset.com      0
1  https://www.realbusinessrescue.co.uk      0
2            https://sentinelpeakrv.com      0
3             http://www.chesspals.com/      0
4         https://www.marengo.k12.al.us      0

In [40]:
df2['label'].unique()

array([0, 1])

## 3- Dataset

In [8]:
df3 = pd.read_csv('OWS_URL_DS.csv')

In [9]:
df3.head()

,uid,url,label,sublabel
0,e94caff6-0b7a-45b6-999c-6b3545c9861a,https://www.imzog.com/en/all/latest/,Adult,Adult
1,2659a22b-a33c-4723-a119-8b18568bac60,https://www.imzog.com/en/all/,Adult,Adult
2,14b17b9f-0d77-49b5-8e70-819ebb74be70,http://www.wifesinterracialmovies.com/cgi-bin/...,Adult,Adult
3,4e5e6d29-28f4-4a46-a866-fc880625cccc,http://www.wifesinterracialmovies.com/mywifepo...,Adult,Adult
4,b8c120b7-3f2a-42ee-84f5-2110923a2e74,http://www.wifesinterracialmovies.com/mywifepo...,Adult,Adult

In [17]:
df3['label'].unique()

array(['Adult', 'Benign', 'Malicious'], dtype=object)

In [18]:
df3['sublabel'].unique()

array(['Adult', 'Society', 'Kids_and_Teens', 'Regional', 'Sports',
       'Health', 'Science', 'Business', 'Reference', 'Shopping',
       'Computers', 'Arts', 'News', 'Recreation', 'Games', 'Home',
       'Phishing', 'Malware', 'Defacement', 'Spam', 'Risky'], dtype=object)

In [23]:
df3 = df3[['url', 'label']]

In [37]:
df3['label'] = df3['label'].map({'Benign': 0, 'Adult': 1,'Malicious': 1})

In [38]:
df3.head()

                                                 url  label
0               https://www.imzog.com/en/all/latest/      1
1                      https://www.imzog.com/en/all/      1
2  http://www.wifesinterracialmovies.com/cgi-bin/...      1
3  http://www.wifesinterracialmovies.com/mywifepo...      1
4  http://www.wifesinterracialmovies.com/mywifepo...      1

In [39]:
df3['label'].unique()

array([1, 0])

## 4- Dataset

In [10]:
df4 = pd.read_csv('Webpages_Classification_train_data.csv')

In [11]:
df4.head()

,Unnamed: 0,url,url_len,ip_add,geo_loc,tld,who_is,https,js_len,js_obf_len,content,label
0,0,http://members.tripod.com/russiastation/,40,42.77.221.155,Taiwan,com,complete,yes,58.0,0.0,Named themselves charged particles in a manly ...,good
1,1,http://www.ddj.com/cpp/184403822,32,3.211.202.180,United States,com,complete,yes,52.5,0.0,And filipino field \n \n \n \n \n \n \n \n the...,good
2,2,http://www.naef-usa.com/,24,24.232.54.41,Argentina,com,complete,yes,103.5,0.0,"Took in cognitivism, whose adherents argue for...",good
3,3,http://www.ff-b2b.de/,21,147.22.38.45,United States,de,incomplete,no,720.0,532.8,fire cumshot sodomize footaction tortur failed...,bad
4,4,http://us.imdb.com/title/tt0176269/,35,205.30.239.85,United States,com,complete,yes,46.5,0.0,"Levant, also monsignor georges. In 1800, lists...",good

In [16]:
df4['label'].unique()

array(['good', 'bad'], dtype=object)

In [25]:
df4 = df4[['url', 'label']]

In [41]:
df4['label']=df4['label'].map({'good':0,'bad':1})

In [42]:
df4.head()

                                        url  label
0  http://members.tripod.com/russiastation/      0
1          http://www.ddj.com/cpp/184403822      0
2                  http://www.naef-usa.com/      0
3                     http://www.ff-b2b.de/      1
4       http://us.imdb.com/title/tt0176269/      0

In [43]:
df4['label'].unique()

array([0, 1])

## 5- Dataset

In [12]:
df5 = pd.read_csv('website_classification.csv')

In [13]:
df5.head()

,Unnamed: 0,website_url,cleaned_website_text,Category
0,0,https://www.booking.com/index.html?aid=1743217,official site good hotel accommodation big sav...,Travel
1,1,https://travelsites.com/expedia/,expedia hotel book sites like use vacation wor...,Travel
2,2,https://travelsites.com/tripadvisor/,tripadvisor hotel book sites like previously d...,Travel
3,3,https://www.momondo.in/?ispredir=true,cheap flights search compare flights momondo f...,Travel
4,4,https://www.ebookers.com/?AFFCID=EBOOKERS-UK.n...,bot create free account create free account si...,Travel

In [15]:
df5['Category'].unique()

array(['Travel', 'Social Networking and Messaging', 'News',
       'Streaming Services', 'Sports', 'Photography',
       'Law and Government', 'Health and Fitness', 'Games', 'E-Commerce',
       'Forums', 'Food', 'Education', 'Computers and Technology',
       'Business/Corporate', 'Adult'], dtype=object)

In [31]:
df5 = df5[['website_url', 'Category']]
df5.columns = ['url', 'label']

In [45]:
df5['label'] = (df5['label'] == 'Adult').astype(int)

In [46]:
df5.head()

                                                 url  label
0     https://www.booking.com/index.html?aid=1743217      0
1                   https://travelsites.com/expedia/      0
2               https://travelsites.com/tripadvisor/      0
3              https://www.momondo.in/?ispredir=true      0
4  https://www.ebookers.com/?AFFCID=EBOOKERS-UK.n...      0

In [47]:
df5['label'].unique()

array([0, 1])

## Concatenating All Dataframes to create one

In [48]:
df = pd.concat([df2, df3, df4, df5], ignore_index=True)

In [49]:
df.head()

                                    url  label
0         https://www.alaskansunset.com      0
1  https://www.realbusinessrescue.co.uk      0
2            https://sentinelpeakrv.com      0
3             http://www.chesspals.com/      0
4         https://www.marengo.k12.al.us      0

## Feature Engineering

#### Length Based Features

In [50]:
df['url_length'] = df['url'].str.len()

long urls -> suspicious

##### Special Character counts

In [51]:
df['dot_count'] = df['url'].str.count(r'\.')
df['dash_count'] = df['url'].str.count('-')
df['slash_count'] = df['url'].str.count('/')
df['at_count'] = df['url'].str.count('@')

too much symbols -> Spam/Phishing patterns

#### Ratio of digits in URLs

In [52]:
def digit_ratio(url):
    digits = sum(c.isdigit() for c in url)
    return digits / len(url)

df['digit_ratio'] = df['url'].apply(digit_ratio)

greater digits ratio in URL are risky

## Checking for IP address in URL

In [53]:
df['has_ip'] = df['url'].str.contains(r'\d+\.\d+\.\d+\.\d+').astype(int)

URLs having IP addresses are often malicious

#### Suspicious Keyword Detection

In [54]:
bad_words = ['porn','xxx','sex','adult','nude','naked','boobs','breast','escort',
    'cam','cams','webcam','livecam','onlyfans','xvideo','xnxx','redtube',
    'hentai','bdsm','fetish','milf','teen','erotic','strip','stripchat','casino','bet','betting','poker','slot','jackpot','roulette',
    'blackjack','win','winnings','bonus','freebet','odds','gamble', 'free','offer','click','login','signup','verify','account',
    'secure','update','bonus','gift','promo','cheap','deal', 's3x','p0rn','pr0n','xxx','xnx','sexx','pron','sexyy']
def check_bad_words(url):
    url = str(url).lower()
    for w in bad_words:
        if w in url:
            return 1
    return 0

df['has_bad_word'] = df['url'].apply(check_bad_words)

#### Checking for Https protocol

In [55]:
def check_https(url):
    url = str(url).lower()
    if 'https' in url:
        return 1
    return 0

df['has_https'] = df['url'].apply(check_https)

URLs usinhg https are relatively safer

In [56]:
df.head()

,url,label,url_length,dot_count,dash_count,slash_count,at_count,digit_ratio,has_ip,has_bad_word,has_https
0,https://www.alaskansunset.com,0,29,2,0,2,0,0.000000,0,0,1
1,https://www.realbusinessrescue.co.uk,0,36,3,0,2,0,0.000000,0,0,1
2,https://sentinelpeakrv.com,0,26,1,0,2,0,0.000000,0,0,1
3,http://www.chesspals.com/,0,25,2,0,3,0,0.000000,0,0,0
4,https://www.marengo.k12.al.us,0,29,4,0,2,0,0.068966,0,0,1

## Saving Dataframe

In [57]:
df.to_csv('web_data.csv')