In [2]:
import pandas as pd

In [3]:
df1 = pd.read_csv('Suicide_Detection.csv')

In [4]:
df1.head()

   Unnamed: 0                                               text        class
0           2  Ex Wife Threatening SuicideRecently I left my ...      suicide
1           3  Am I weird I don't get affected by compliments...  non-suicide
2           4  Finally 2020 is almost over... So I can never ...  non-suicide
3           8          i need helpjust help me im crying so hard      suicide
4           9  I’m so lostHello, my name is Adam (16) and I’v...      suicide

In [5]:
df1 = df1.drop(df1.columns[0], axis=1)

In [6]:
df1.head()

                                                text        class
0  Ex Wife Threatening SuicideRecently I left my ...      suicide
1  Am I weird I don't get affected by compliments...  non-suicide
2  Finally 2020 is almost over... So I can never ...  non-suicide
3          i need helpjust help me im crying so hard      suicide
4  I’m so lostHello, my name is Adam (16) and I’v...      suicide

In [7]:
df1['label'] = df1['class'].map({'suicide': 'suicide', 'non-suicide': 'normal'})

In [8]:
df1.head()

                                                text        class    label
0  Ex Wife Threatening SuicideRecently I left my ...      suicide  suicide
1  Am I weird I don't get affected by compliments...  non-suicide   normal
2  Finally 2020 is almost over... So I can never ...  non-suicide   normal
3          i need helpjust help me im crying so hard      suicide  suicide
4  I’m so lostHello, my name is Adam (16) and I’v...      suicide  suicide

In [9]:
df2 =pd.read_csv('cyberbullying_tweets.csv')

In [10]:
df2.head()

                                          tweet_text cyberbullying_type
0  In other words #katandandre, your food was cra...  not_cyberbullying
1  Why is #aussietv so white? #MKR #theblock #ImA...  not_cyberbullying
2  @XochitlSuckkks a classy whore? Or more red ve...  not_cyberbullying
3  @Jason_Gio meh. :P  thanks for the heads up, b...  not_cyberbullying
4  @RudhoeEnglish This is an ISIS account pretend...  not_cyberbullying

In [11]:
df2.columns = ['text', 'class']

In [12]:
df2.head()

                                                text              class
0  In other words #katandandre, your food was cra...  not_cyberbullying
1  Why is #aussietv so white? #MKR #theblock #ImA...  not_cyberbullying
2  @XochitlSuckkks a classy whore? Or more red ve...  not_cyberbullying
3  @Jason_Gio meh. :P  thanks for the heads up, b...  not_cyberbullying
4  @RudhoeEnglish This is an ISIS account pretend...  not_cyberbullying

In [13]:
df2['label'] = df2['class'].map({'not_cyberbullying': 'normal', 'cyberbullying': 'bullying'})

In [14]:
df2.head()

,text,class,label
0,"In other words #katandandre, your food was cra...",not_cyberbullying,normal
1,Why is #aussietv so white? #MKR #theblock #ImA...,not_cyberbullying,normal
2,@XochitlSuckkks a classy whore? Or more red ve...,not_cyberbullying,normal
3,"@Jason_Gio meh. :P thanks for the heads up, b...",not_cyberbullying,normal
4,@RudhoeEnglish This is an ISIS account pretend...,not_cyberbullying,normal

In [15]:
df4= pd.read_csv('labeled_data.csv ')

In [16]:
df4.head()

,Unnamed: 0,count,hate_speech,offensive_language,neither,class,tweet
0,0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...
1,1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2,2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3,3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4,4,6,0,6,0,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [17]:
df4 = df4[['class','tweet']]

In [18]:
df4.head()

   class                                              tweet
0      2  !!! RT @mayasolovely: As a woman you shouldn't...
1      1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2      1  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3      1  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4      1  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [19]:
df4.columns= ['class','text']

In [20]:
df4['label'] = df4['class'].map({1:'hate',1:'bullying',2:'hate'})

In [21]:
df4.head()

   class                                               text     label
0      2  !!! RT @mayasolovely: As a woman you shouldn't...      hate
1      1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  bullying
2      1  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  bullying
3      1  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  bullying
4      1  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...  bullying

In [24]:
final_df = pd.concat([df1[['text','label']], df2[['text','label']], df4[['text','label']]])

In [25]:
final_df

                                                    text     label
0      Ex Wife Threatening SuicideRecently I left my ...   suicide
1      Am I weird I don't get affected by compliments...    normal
2      Finally 2020 is almost over... So I can never ...    normal
3              i need helpjust help me im crying so hard   suicide
4      I’m so lostHello, my name is Adam (16) and I’v...   suicide
...                                                  ...       ...
24778  you's a muthaf***in lie &#8220;@LifeAsKing: @2...  bullying
24779  you've gone and broke the wrong heart baby, an...      hate
24780  young buck wanna eat!!.. dat nigguh like I ain...  bullying
24781              youu got wild bitches tellin you lies  bullying
24782  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...      hate

[304549 rows x 2 columns]

In [26]:
final_df.to_csv("chat_dataset.csv", index=False)